### PR TITLE
include dbgsym packages

### LINKED ISSUE #331: no support for -dbgsym packages
In stretch, debian added support for dbgsym packages [1].  Here is some sample output.  Packages are built with debuild.

```
aptly repo include -no-remove-files=true -config=../aptly.conf -repo=stretch artifacts
gpgv: Signature made Wed 06 Jan 2016 10:11:54 PM CST using DSA key ID A8AC8032
gpgv: Good signature from "Gary Kramlich (grim) <grim@reaperworld.com>"
Loading repository stretch for changes file gplugin_0.0.21_amd64.changes...
[+] gir1.2-gplugin-0.0_0.0.21_amd64 added
[+] gplugin_0.0.21_source added
[+] libgplugin-dev_0.0.21_amd64 added
[!] libgplugin-gtk-bin-dbgsym_0.0.21_amd64 has been ignored as it doesn't match restriction
[+] libgplugin-gtk-bin_0.0.21_amd64 added
[+] libgplugin-gtk-dev_0.0.21_amd64 added
[+] libgplugin-gtk0-dbg_0.0.21_amd64 added
[+] libgplugin-gtk0_0.0.21_amd64 added
[+] libgplugin-loaders_0.0.21_all added
[!] libgplugin-lua-dbgsym_0.0.21_amd64 has been ignored as it doesn't match restriction
[+] libgplugin-lua_0.0.21_amd64 added
[!] libgplugin-python-dbgsym_0.0.21_amd64 has been ignored as it doesn't match restriction
[+] libgplugin-python_0.0.21_amd64 added
[+] libgplugin0-dbg_0.0.21_amd64 added
[+] libgplugin0_0.0.21_amd64 added
[!] Some files were skipped due to errors:
  artifacts/libgplugin-gtk-bin-dbgsym_0.0.21_amd64.deb
  artifacts/libgplugin-lua-dbgsym_0.0.21_amd64.deb
  artifacts/libgplugin-python-dbgsym_0.0.21_amd64.deb
ERROR: some files failed to be added
```

I've been trying to figure out how the package restrictions work, but so far haven't been able to grok it enough to fix it.

[1] https://wiki.debian.org/AutomaticDebugPackages

### PR DESCRIPTION
**Pull request by sobczyk**
fixes #331

package should pass name query and same source query

### CODE REVIEW

File: deb/changes.go [hunk 1]
```diff
@@ -186,6 +186,18 @@ func (c *Changes) PackageQuery() (PackageQuery, error) {
 			}
 		}
 
+		// matching debug ddeb packages, they're not present in the Binary field
+		var ddebQuery PackageQuery
+		ddebQuery = &AndQuery{
+			L: &FieldQuery{Field: "Name", Relation: VersionPatternMatch, Value: "*-dbgsym"},
```
Comment (smira) [inline deb/changes.go]: I think that's too broad here, I would suggest to use `for` loop above to add `binary + "-dbgsym"` query

Also unit-tests are failing.

Thanks for the PR!
